name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd drivingschool/
            git pull
            MYSQL_PWD=${{ secrets.MYSQL_PASSWORD }} mysql -u root drivingschool < sql/schema.sql
            pm2 restart all
            sudo systemctl reload nginx
